In [88]:
# First off, we have to insert our packages, and this is the code to do it.
import pandas as pd
# Then, to load our data and make sure we are using the right resource, we copy it exactly from our given resource.
air_data = pd.read_csv('AirQuality_Daily_StudentVersion.csv')

In [89]:
# This is to turn our data into a data frame.
air_data = pd.DataFrame(air_data)

In [8]:
# This line will make it so the voc data at the end is grouped by sensor names.
voc_grouped = air_data.groupby('sensor.name')

# This will make it so that the grouped data has a statistical summary that gives me the four main statistics.
air_data_voc = voc_grouped.agg(max = ('voc', 'max'),
                                                    min = ('voc', 'min'),
                                                    mean = ('voc', 'mean'),
                                                    median = ('voc', 'median'))

# After getting the main statistics, this will make it so that they are sorting by mean and by the highest top 5 voc.
top5_mean_voc = (
    air_data_voc.sort_values(by = 'mean', ascending = False) #sort_values sorts some column that i need to specify
)
top5_mean_voc.head(5)

# This will do the same thing, but by median this time.
top5_median_voc = (
    air_data_voc.sort_values(by = 'median', ascending = False) #sort_values sorts some column that i need to specify
)
top5_median_voc.head(5)

,max,min,mean,median
sensor.name,,,,
Swnphd-ogallala,1209.931571,61.427708,399.434240,423.082292
Swnphd-mccook,849.734917,0.000000,353.941581,381.468479
Three Rivers Public Health Department,741.876042,50.000000,370.216208,376.810167
FCHD-YPS,856.012625,54.998000,372.462720,375.383500
ELVPHD Norfolk HD 4,884.649000,0.000000,360.833744,368.580500

In [15]:
# This line will make it so the pm2.5_atm data at the end is grouped by sensor names.
PM25_grouped = air_data.groupby('sensor.name')

# This will make it so that the grouped data has a statistical summary that gives me the four main statistics.
air_data_PM25 = PM25_grouped.agg(max = ('pm2.5_atm', 'max'),
                                                    min = ('pm2.5_atm', 'min'),
                                                    mean = ('pm2.5_atm', 'mean'),
                                                    median = ('pm2.5_atm', 'median'))

# After getting the main statistics, this will make it so that they are sorting by mean and by the highest top 5 voc.
top5_mean_PM25 = (
    air_data_PM25.sort_values(by = 'mean', ascending = False) #sort_values sorts some column that i need to specify
)
top5_mean_PM25.head(5)

# This will do the same thing, but by median this time.
top5_median_PM25 = (
    air_data_PM25.sort_values(by = 'median', ascending = False) #sort_values sorts some column that i need to specify
)
top5_median_PM25.head(5)

,max,min,mean,median
sensor.name,,,,
Broken Bow,3205.868854,0.019187,928.710593,36.050240
#16 - Richardson County Courthouse,3782.823313,0.243729,700.127342,11.977344
#18 - Southeast District Health Department- Tecumseh,2987.467563,0.140708,613.175352,10.322875
ELVPHD Norfolk HD 4,79.972917,0.307896,13.369492,9.706229
ELVPHD Wisner HD 5,51.984812,0.154271,11.154420,8.464583

In [16]:
# This line will make it so the pm10.0_atm data at the end is grouped by sensor names.
PM10_grouped = air_data.groupby('sensor.name')

# This will make it so that the grouped data has a statistical summary that gives me the four main statistics.
air_data_PM10 = PM10_grouped.agg(max = ('pm10.0_atm', 'max'),
                                                    min = ('pm10.0_atm', 'min'),
                                                    mean = ('pm10.0_atm', 'mean'),
                                                    median = ('pm10.0_atm', 'median'))

# After getting the main statistics, this will make it so that they are sorting by mean and by the highest top 5 pm10.0_atm.
top5_mean_PM10 = (
    air_data_PM10.sort_values(by = 'mean', ascending = False) #sort_values sorts some column that i need to specify
)
top5_mean_PM10.head(5)

# This will do the same thing, but by pm10.0_atm median this time.
top5_median_PM10 = (
    air_data_PM10.sort_values(by = 'median', ascending = False) #sort_values sorts some column that i need to specify
)
top5_median_PM10.head(5)

,max,min,mean,median
sensor.name,,,,
Broken Bow,3206.779708,0.089917,929.678512,43.179094
#16 - Richardson County Courthouse,3784.682542,0.473583,701.632446,13.305615
ELVPHD Norfolk HD 4,95.131583,0.756229,15.969341,11.474708
#18 - Southeast District Health Department- Tecumseh,2988.441438,0.205729,614.227248,11.433729
ELVPHD Wisner HD 5,75.461354,0.698958,14.462116,10.935958

In [157]:
#This will group the air data by the date so we can see when the max pm2.5_atm happened 
air_data_grouped = (air_data.groupby('date'))

# This will aggregate the data so it is pm2.5_atm by the max value statistic 
air_data_pm25 = air_data_grouped.agg(max = ('pm2.5_atm', 'max'))

# This will give us the top 5 max pm2.5_atms within the data set
top5_max_pm25 = (
    air_data_pm25.sort_values(by = 'max', ascending = False) #sort_values sorts some column that i need to specify
)
top5_max_pm25.head(5)

                  max
date
02/18/25  3782.823313
02/19/25  3401.999333
02/20/25  3243.746646
01/21/25  3209.817146
01/20/25  3087.149167

In [34]:
# This will group the air data by the sensor so we can see where the max pm2.5_atm happened 
air_data_grouped = air_data.groupby('sensor.name')

# This will aggregate the data so it is pm2.5_atm by the max value statistic
air_data_pm25 = air_data_grouped.agg(max = ('pm2.5_atm', 'max'))

# This will give us the top 5 max pm2.5_atms within the data set
top5_max_pm25 = (
    air_data_pm25.sort_values(by = 'max', ascending = False) #sort_values sorts some column that i need to specify
)
top5_max_pm25.head(5)

                                                            max
sensor.name
#16 - Richardson County Courthouse                  3782.823313
Broken Bow                                          3205.868854
Swnphd-mccook                                       3053.114292
#18 - Southeast District Health Department- Tec...  2987.467563
TRPHD Dawson Co. Courthouse 25                      2363.017646

In [32]:
# This will group the air data by the date so we can see when the max pm10.0_atm happened 
air_data_grouped = air_data.groupby('date')

# This will aggregate the data so it is pm10.0_atm by the max value statistic
air_data_pm10 = air_data_grouped.agg(max = ('pm10.0_atm', 'max'))

# This will give us the top 5 max pm10.0_atms within the data set
top5_max_pm10 = (
    air_data_pm10.sort_values(by = 'max', ascending = False) #sort_values sorts some column that i need to specify
)
top5_max_pm10.head(5)

                  max
date
02/18/25  3784.682542
02/19/25  3403.435958
02/20/25  3245.613354
01/21/25  3211.046813
01/20/25  3088.053896

In [35]:
# This will group the air data by the sensor name so we can see where the max pm10.0_atm happened 
air_data_grouped = air_data.groupby('sensor.name')

# This will aggregate the data so it is pm10.0_atm by the max value statistic
air_data_pm10 = air_data_grouped.agg(max = ('pm10.0_atm', 'max'))

# This will give us the top 5 max pm10.0_atms within the data set
top5_max_pm10 = (
    air_data_pm10.sort_values(by = 'max', ascending = False) #sort_values sorts some column that i need to specify
)
top5_max_pm10.head(5)

                                                            max
sensor.name
#16 - Richardson County Courthouse                  3784.682542
Broken Bow                                          3206.779708
Swnphd-mccook                                       3054.484250
#18 - Southeast District Health Department- Tec...  2988.441438
TRPHD Dawson Co. Courthouse 25                      2367.085500

In [158]:
# This will group the air data by the date so we can see when the max voc happened 
air_data_grouped = air_data.groupby('date')

# This will aggregate the data so it is voc by the max value statistic
air_data_voc = air_data_grouped.agg(max = ('voc', 'max'))                           

# This will give us the top 5 max voc within the data set
top5_max_voc = (
    air_data_voc.sort_values(by = 'max', ascending = False) #sort_values sorts some column that i need to specify
)
top5_max_voc.head(5)

                  max
date
06/24/24  1209.931571
10/05/24  1135.473000
11/23/24  1041.722000
10/12/24   884.649000
10/16/24   871.182000

In [48]:
# This will group the air data by the sensor name so we can see where the max voc happened
air_data_grouped = air_data.groupby('sensor.name')

# This will aggregate the data so it is voc by the max value statistic
air_data_voc = air_data_grouped.agg(max = ('voc', 'max'))

# This will sort the top 5 vocs within the data set
top5_max_voc = (
    air_data_voc.sort_values(by = 'max', ascending = False) #sort_values sorts some column that i need to specify
)
top5_max_voc.head(5)

                             max
sensor.name
Swnphd-ogallala      1209.931571
SWNPHD-Imerial       1135.473000
ELVPHD Norfolk HD 4   884.649000
FCHD-YPS              856.012625
Swnphd-mccook         849.734917

In [165]:
# This will give humidity a function that assigns humidity levels
def assign_humidity(humidity): 
    if humidity < 50: 
        return 'Low' 
    elif 51 <= humidity <= 80: 
        return 'High' 
    elif 80 <= humidity <= 100:
        return 'Very High' # Humidity above 80 is Very High

# Application of the Function
air_data['humidity_level'] = air_data['humidity'].apply(assign_humidity)

# Group by sensor name and humidity level
humidity_by_sensor = (air_data.groupby(['sensor.name', 'humidity_level']).size())
humidity_by_sensor

sensor.name                                                   humidity_level
#16 - Richardson County Courthouse                            High               16
                                                              Low               167
                                                              Very High           8
#17 - Otoe County                                             High               34
                                                              Low               259
#18 - Southeast District Health Department- Tecumseh          High               15
                                                              Low               166
Ainsworth Public School #9                                    High               17
                                                              Low               348
Broken Bow                                                    High               65
                                                              Low               279
                                                              Very High          18
Buffalo County TRPHD #26                                      High               28
                                                              Low               328
ELVPHD Norfolk HD 4                                           High               32
                                                              Low               125
                                                              Very High           3
ELVPHD Tekamah HD 3                                           High               33
                                                              Low               166
ELVPHD Wisner HD 5                                            High               73
                                                              Low                65
                                                              Very High          22
FCHD-YPS                                                      High               67
                                                              Low               283
Laurel High School                                            High               17
                                                              Low               148
Loup Basin Public Health Department                           High               23
                                                              Low               363
Lower Niobrara NRD Butte 10                                   High               22
                                                              Low               345
NCDHD O'Neill #11                                             High               29
                                                              Low               192
PHS Fairbury JCHL 13                                          High               68
                                                              Low               247
                                                              Very High           8
SWNPHD-Imerial                                                High               29
                                                              Low               247
                                                              Very High           4
South Heartland District Health Dept. Hastings office         High               16
                                                              Low               359
South Heartland District Health Dept. Superior City Building  High               15
                                                              Low               266
Swnphd-Benklemen                                              High               31
                                                              Low               351
Swnphd-mccook                                                 High               13
                                                              Low               376
Swnphd-ogallala                                               High               10
                                                              Low               364
TRPHD Dawson Co. Courthouse 25                                High               66
                                                              Low               315
TRPHD Harlan Co. Courthouse 24                                High               31
                                                              Low               331
Three Rivers Public Health Department                         High               29
                                                              Low               343
WCDHD Arthur High School 28                                   High               11
                                                              Low               304
WCDHD City Building                                           High                6
                                                              Low                97
WCDHD Thedford Library 29                                     High               19
                                                              Low               124
dtype: int64

In [166]:
# This will give temperature a function that assigns temperature levels
def assign_temperature(temperature): 
    if temperature < 32: 
        return 'Below Freezing'
    elif 32 <= temperature <= 50:
        return 'Cool'
    elif 50 <= temperature <= 70:
        return 'Warm'
    elif 70 <= temperature <= 150:
        return 'Hot'
        
# Application of the Function
air_data['temperature_level'] = air_data['temperature'].apply(assign_temperature)

# Group by sensor name and humidity level
temperature_by_sensor = (air_data.groupby(['sensor.name', 'temperature_level']).size())
temperature_by_sensor

sensor.name                         temperature_level
#16 - Richardson County Courthouse  Hot                  175
                                    Warm                  18
#17 - Otoe County                   Below Freezing        27
                                    Cool                  50
                                    Hot                  149
                                                        ...
WCDHD City Building                 Warm                  48
WCDHD Thedford Library 29           Below Freezing        22
                                    Cool                  32
                                    Hot                   57
                                    Warm                  36
Length: 104, dtype: int64

In [167]:
def assign_PM25(PM25): 
    if PM25 < 12: 
        return 'Good'
    elif 12 <= PM25 <= 35.4:
        return 'Moderate'
    elif 35.4 <= PM25 <= 55.4:
        return 'Unhealthy for Sensitive Group'
    elif 55.4 <= PM25 <= 150.4:
        return 'Unhealthy'
    elif 150.4 <= PM25 <= 250.4:
        return 'Very Unhealthy' 
    elif 250.4 <= PM25 <= 1000:
        return 'Hazardous'
air_data['pm2.5_AQI'] = air_data['pm2.5_atm'].apply(assign_PM25)
air_data
pm25_by_sensor = (air_data.groupby(['sensor.name', 'pm2.5_AQI']).size())
pm25_by_sensor

sensor.name                         pm2.5_AQI
#16 - Richardson County Courthouse  Good                             159
                                    Hazardous                          5
                                    Moderate                          52
                                    Unhealthy                          4
                                    Unhealthy for Sensitive Group      1
                                                                    ...
WCDHD City Building                 Good                             100
                                    Moderate                           3
WCDHD Thedford Library 29           Good                             123
                                    Moderate                          23
                                    Unhealthy for Sensitive Group      1
Length: 95, dtype: int64

In [168]:

def assign_PM10(PM10): 
    if PM10 < 54: 
        return 'Good'
    elif 54 <= PM10 <= 154:
        return 'Moderate'
    elif 154 <= PM10 <= 254:
        return 'Unhealthy for Sensitive Group'
    elif 254 <= PM10 <= 354:
        return 'Unhealthy'
    elif 354 <= PM10 <= 424:
        return 'Very Unhealthy' 
    elif 424 <= PM10 <= 1000:
        return 'Hazardous'
air_data['pm10.0_AQI'] = air_data['pm10.0_atm'].apply(assign_PM10)
pm10_by_sensor = (air_data.groupby(['sensor.name', 'pm10.0_AQI']).size())
pm10_by_sensor

sensor.name                                                   pm10.0_AQI
#16 - Richardson County Courthouse                            Good                             212
                                                              Hazardous                          2
                                                              Moderate                           4
                                                              Unhealthy                          1
                                                              Unhealthy for Sensitive Group      1
                                                              Very Unhealthy                     1
#17 - Otoe County                                             Good                             302
#18 - Southeast District Health Department- Tecumseh          Good                             126
                                                              Moderate                           1
Ainsworth Public School #9                                    Good                             368
Broken Bow                                                    Good                             189
                                                              Moderate                           3
                                                              Unhealthy                          1
Buffalo County TRPHD #26                                      Good                             359
ELVPHD Norfolk HD 4                                           Good                             168
                                                              Moderate                           3
ELVPHD Tekamah HD 3                                           Good                             201
                                                              Moderate                           1
ELVPHD Wisner HD 5                                            Good                             351
                                                              Moderate                           6
FCHD-YPS                                                      Good                             363
                                                              Moderate                           1
                                                              Very Unhealthy                     1
Laurel High School                                            Good                             172
Loup Basin Public Health Department                           Good                             387
                                                              Moderate                           1
                                                              Unhealthy for Sensitive Group      1
Lower Niobrara NRD Butte 10                                   Good                             371
NCDHD O'Neill #11                                             Good                             202
                                                              Moderate                           3
PHS Fairbury JCHL 13                                          Good                             347
                                                              Moderate                           1
SWNPHD-Imerial                                                Good                             282
                                                              Moderate                           2
South Heartland District Health Dept. Hastings office         Good                             376
                                                              Moderate                           1
South Heartland District Health Dept. Superior City Building  Good                             286
Swnphd-Benklemen                                              Good                             385
                                                              Moderate                           2
                                                              Unhealthy for Sensitive Group      1
Swnphd-mccook                                                 Good                             361
                                                              Hazardous                          9
                                                              Moderate                           1
Swnphd-ogallala                                               Good                             373
                                                              Moderate                           1
                                                              Unhealthy for Sensitive Group      1
TRPHD Dawson Co. Courthouse 25                                Good                             382
                                                              Hazardous                          1
                                                              Moderate                           1
                                                              Unhealthy                          1
                                                              Very Unhealthy                     1
TRPHD Harlan Co. Courthouse 24                                Good                             367
Three Rivers Public Health Department                         Good                             375
                                                              Moderate                           2
WCDHD Arthur High School 28                                   Good                             319
                                                              Moderate                           1
WCDHD City Building                                           Good                             103
WCDHD Thedford Library 29                                     Good                             147
dtype: int64

In [175]:
# This will make columns so that it can filtered to compare pm10.0_AQI to other data
cols = ['date', 'sensor.name', 'pm10.0_atm', 'pm10.0_AQI', 'humidity_level', 'temperature_level']
filtered = (air_data[air_data['pm10.0_AQI'] == 'Unhealthy for Sensitive Group']
            .loc[:, cols]
            .sort_values(by = 'sensor.name'))
filtered

,date,sensor.name,pm10.0_atm,pm10.0_AQI,humidity_level,temperature_level
6076,12/08/24,#16 - Richardson County Courthouse,200.798396,Unhealthy for Sensitive Group,None,None
2144,06/14/24,Loup Basin Public Health Department,231.757021,Unhealthy for Sensitive Group,Low,Hot
2443,06/27/24,Swnphd-Benklemen,188.977500,Unhealthy for Sensitive Group,Low,Hot
4285,09/11/24,Swnphd-ogallala,154.910438,Unhealthy for Sensitive Group,Low,Hot

In [177]:
cols = ['date', 'sensor.name', 'pm2.5_atm', 'pm2.5_AQI', 'humidity_level', 'temperature_level', 'monitor_index']
filtered = (air_data[air_data['pm2.5_AQI'] == 'Unhealthy for Sensitive Group']
            .loc[:, cols]
            .sort_values(by = 'sensor.name', ascending = False))
filtered

,date,sensor.name,pm2.5_atm,pm2.5_AQI,humidity_level,temperature_level,monitor_index
7498,02/15/25,WCDHD Thedford Library 29,36.138729,Unhealthy for Sensitive Group,High,Below Freezing,195331
3102,07/23/24,WCDHD Arthur High School 28,41.983833,Unhealthy for Sensitive Group,Low,Hot,195355
3177,07/26/24,WCDHD Arthur High School 28,38.395812,Unhealthy for Sensitive Group,Low,Hot,195355
3127,07/24/24,WCDHD Arthur High School 28,43.357542,Unhealthy for Sensitive Group,Low,Hot,195355
3077,07/22/24,WCDHD Arthur High School 28,37.543625,Unhealthy for Sensitive Group,Low,Hot,195355
3152,07/25/24,WCDHD Arthur High School 28,46.354292,Unhealthy for Sensitive Group,Low,Hot,195355
1359,05/14/24,Three Rivers Public Health Department,51.491208,Unhealthy for Sensitive Group,Low,Hot,195367
6407,12/24/24,Three Rivers Public Health Department,42.264313,Unhealthy for Sensitive Group,Low,Cool,195367
3790,08/20/24,Three Rivers Public Health Department,38.130938,Unhealthy for Sensitive Group,Low,Hot,195367
7508,02/15/25,Three Rivers Public Health Department,37.249500,Unhealthy for Sensitive Group,High,Cool,195367
3774,08/20/24,TRPHD Harlan Co. Courthouse 24,36.870792,Unhealthy for Sensitive Group,Low,Hot,195315
3165,07/26/24,TRPHD Harlan Co. Courthouse 24,39.998833,Unhealthy for Sensitive Group,Low,Hot,195315
529,04/06/24,TRPHD Harlan Co. Courthouse 24,37.819938,Unhealthy for Sensitive Group,Low,Warm,195315
3140,07/25/24,TRPHD Harlan Co. Courthouse 24,42.725625,Unhealthy for Sensitive Group,Low,Hot,195315
3120,07/24/24,TRPHD Dawson Co. Courthouse 25,36.111646,Unhealthy for Sensitive Group,Low,Hot,195333
3170,07/26/24,TRPHD Dawson Co. Courthouse 25,41.228375,Unhealthy for Sensitive Group,Low,Hot,195333
3145,07/25/24,TRPHD Dawson Co. Courthouse 25,46.411146,Unhealthy for Sensitive Group,Low,Hot,195333
8180,03/19/25,TRPHD Dawson Co. Courthouse 25,47.437771,Unhealthy for Sensitive Group,Low,Cool,195333
3780,08/20/24,TRPHD Dawson Co. Courthouse 25,38.864196,Unhealthy for Sensitive Group,High,Hot,195333
3803,08/21/24,TRPHD Dawson Co. Courthouse 25,36.075479,Unhealthy for Sensitive Group,High,Hot,195333
3160,07/25/24,Swnphd-ogallala,47.412542,Unhealthy for Sensitive Group,Low,Hot,195541
3185,07/26/24,Swnphd-ogallala,38.061646,Unhealthy for Sensitive Group,Low,Hot,195541
3135,07/24/24,Swnphd-ogallala,43.837667,Unhealthy for Sensitive Group,Low,Hot,195541
544,04/06/24,Swnphd-ogallala,39.169042,Unhealthy for Sensitive Group,Low,Warm,195541
3085,07/22/24,Swnphd-ogallala,37.444458,Unhealthy for Sensitive Group,Low,Hot,195541
3110,07/23/24,Swnphd-ogallala,40.816833,Unhealthy for Sensitive Group,Low,Hot,195541
3180,07/26/24,Swnphd-mccook,37.059167,Unhealthy for Sensitive Group,Low,Hot,195365
3130,07/24/24,Swnphd-mccook,36.440354,Unhealthy for Sensitive Group,Low,Hot,195365
7836,03/02/25,Swnphd-mccook,35.738500,Unhealthy for Sensitive Group,Low,Warm,195365
3155,07/25/24,Swnphd-mccook,44.073771,Unhealthy for Sensitive Group,Low,Hot,195365
3112,07/24/24,Swnphd-Benklemen,46.913958,Unhealthy for Sensitive Group,Low,Hot,195089
3162,07/26/24,Swnphd-Benklemen,40.402396,Unhealthy for Sensitive Group,Low,Hot,195089
3087,07/23/24,Swnphd-Benklemen,41.126271,Unhealthy for Sensitive Group,Low,Hot,195089
4149,09/06/24,Swnphd-Benklemen,36.178104,Unhealthy for Sensitive Group,Low,Hot,195089
3062,07/22/24,Swnphd-Benklemen,37.702396,Unhealthy for Sensitive Group,Low,Hot,195089
3137,07/25/24,Swnphd-Benklemen,49.938125,Unhealthy for Sensitive Group,Low,Hot,195089
6730,01/09/25,South Heartland District Health Dept. Superior...,39.975313,Unhealthy for Sensitive Group,Low,Below Freezing,195385
7511,02/15/25,South Heartland District Health Dept. Superior...,38.148875,Unhealthy for Sensitive Group,High,Cool,195385
3793,08/20/24,South Heartland District Health Dept. Superior...,40.539417,Unhealthy for Sensitive Group,Low,Hot,195385
3776,08/20/24,South Heartland District Health Dept. Hastings...,41.735646,Unhealthy for Sensitive Group,Low,Hot,195319
1345,05/14/24,South Heartland District Health Dept. Hastings...,47.330646,Unhealthy for Sensitive Group,Low,Hot,195319
3167,07/26/24,South Heartland District Health Dept. Hastings...,38.197646,Unhealthy for Sensitive Group,Low,Hot,195319
3799,08/21/24,South Heartland District Health Dept. Hastings...,35.675229,Unhealthy for Sensitive Group,Low,Hot,195319
3142,07/25/24,South Heartland District Health Dept. Hastings...,37.523708,Unhealthy for Sensitive Group,Low,Hot,195319
1370,05/15/24,South Heartland District Health Dept. Hastings...,38.718854,Unhealthy for Sensitive Group,Low,Hot,195319
3161,07/26/24,SWNPHD-Imerial,38.865437,Unhealthy for Sensitive Group,Low,Hot,194969
3136,07/25/24,SWNPHD-Imerial,49.004625,Unhealthy for Sensitive Group,Low,Hot,194969
3111,07/24/24,SWNPHD-Imerial,45.206938,Unhealthy for Sensitive Group,Low,Hot,194969
3061,07/22/24,SWNPHD-Imerial,36.533854,Unhealthy for Sensitive Group,Low,Hot,194969
3086,07/23/24,SWNPHD-Imerial,40.948458,Unhealthy for Sensitive Group,Low,Hot,194969

In [171]:
cols = ['date', 'sensor.name', 'pm10.0_atm', 'pm10.0_AQI', 'humidity_level', 'temperature_level']
filtered = (air_data[air_data['pm10.0_AQI'] == 'Hazardous']
            .loc[:, cols]
            .sort_values(by = 'sensor.name'))
filtered

,date,sensor.name,pm10.0_atm,pm10.0_AQI,humidity_level,temperature_level
3216,07/28/24,#16 - Richardson County Courthouse,661.886021,Hazardous,Low,Hot
3266,07/30/24,#16 - Richardson County Courthouse,653.352750,Hazardous,Low,Hot
7881,03/04/25,Swnphd-mccook,967.236167,Hazardous,High,Cool
7988,03/09/25,Swnphd-mccook,628.570000,Hazardous,Low,Warm
8127,03/16/25,Swnphd-mccook,883.737438,Hazardous,Low,Warm
8146,03/17/25,Swnphd-mccook,627.240688,Hazardous,Low,Warm
8167,03/18/25,Swnphd-mccook,664.448625,Hazardous,Low,Warm
8232,03/21/25,Swnphd-mccook,858.946250,Hazardous,Low,Cool
8253,03/22/25,Swnphd-mccook,926.086146,Hazardous,Low,Cool
8274,03/23/25,Swnphd-mccook,982.185500,Hazardous,Low,Cool
8295,03/24/25,Swnphd-mccook,564.363833,Hazardous,Low,Cool
7631,02/21/25,TRPHD Dawson Co. Courthouse 25,424.511500,Hazardous,Low,Below Freezing